[[redirects]]
  from = "/api/*"
  to = "http://stash-api-757628238.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api-dev/*"
  to = "http://ec2-3-106-3-86.ap-southeast-2.compute.amazonaws.com:4001/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200